---
title: "Simulation study"
output: 
  html_document:
    theme: flatly
    toc: true
    toc_depth: 3
    toc_float: 
      collapsed: false
vignette: >
  %\VignetteIndexEntry{CausDiscEqVar}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(CausDiscEqVar)
library(ggplot2)
library(tidyr)
library(dplyr)
```


```{r CreateSimData, cache = TRUE, include = FALSE}
data("LowSim")
data("HighSim")
data("ArticleRes")


SIM <- rbind(LowSim, HighSim) %>%
    mutate(Kendall = Kendall * 50 + 50,
           ratio = as.factor(p/n),
           n = as.factor(n)) %>%
    gather("Kendall", "Recall", "Flipped", "FDR", "Hamming",
           key = "PrefMeasure",
           value = "Preformance", factor_key = TRUE)

ARTICLE <- ArticleRes %>%
    mutate(Kendall = Kendall * 50 + 50,
           ratio = as.factor(p/n),
           n = as.factor(n)) %>%
    gather("Kendall", "Recall", "Flipped", "FDR", "Hamming",
           key = "PrefMeasure",
           value = "Preformance", factor_key = TRUE)
```




*** 
***

&nbsp;

# Low Dim: Model Selection

***

## Dense, Top Down
```{r, warning = FALSE, echo = FALSE}
sim <- subset(SIM, 
              graph_setting == "dense" & l == 0.3 & sigma == 1 &
                !is.na(measure) & PrefMeasure != "Hamming" & method == "TD")
art <- subset(ARTICLE,
              graph_setting == "dense" & l == 0.3 &
                PrefMeasure != "Hamming" & method == "TD")

sim <- sim %>% mutate(
  Measure = paste(measure, which, sep = " - ")
)

ggplot() + 
    geom_boxplot(aes(x = n, y = Preformance, color = Measure),
                 data = sim) + 
    facet_grid(p ~ PrefMeasure) + 
    geom_point(aes(x = n, y = Preformance), 
               data = art, color = "black", size = 3) +
    theme(axis.title.y = element_blank())
```


&nbsp;

## Dense, Bottom Up
```{r, warning = FALSE, echo = FALSE}
sim <- subset(SIM, 
              graph_setting == "dense" & l == 0.3 &  sigma == 1 &
                !is.na(measure) & PrefMeasure != "Hamming" & method == "BU")
art <- subset(ARTICLE,
              graph_setting == "dense" & l == 0.3 &
                PrefMeasure != "Hamming" & method == "BU")

sim <- sim %>% mutate(
  Measure = paste(measure, which, sep = " - ")
)

ggplot() + 
    geom_boxplot(aes(x = n, y = Preformance, color = Measure),
                 data = sim) + 
    facet_grid(p ~ PrefMeasure) + 
    geom_point(aes(x = n, y = Preformance), 
               data = art, color = "black", size = 3) +
    theme(axis.title.y = element_blank())
```



&nbsp;

## Sparse, Top Down
```{r, warning = FALSE, echo = FALSE}
sim <- subset(SIM, 
              graph_setting == "sparse" & l == 0.3 &  sigma == 1 &
                !is.na(measure) & PrefMeasure != "Hamming" & method == "TD")
art <- subset(ARTICLE,
              graph_setting == "sparse" & l == 0.3 &
                PrefMeasure != "Hamming" & method == "TD")

sim <- sim %>% mutate(
  Measure = paste(measure, which, sep = " - ")
)

ggplot() + 
    geom_boxplot(aes(x = n, y = Preformance, color = Measure),
                 data = sim) + 
    facet_grid(p ~ PrefMeasure) + 
    geom_point(aes(x = n, y = Preformance), 
               data = art, color = "black", size = 3) +
    theme(axis.title.y = element_blank())
```



&nbsp;

## Sparse, Bottom Up
```{r, warning = FALSE, echo = FALSE}
sim <- subset(SIM, 
              graph_setting == "sparse" & l == 0.3 &  sigma == 1 &
                !is.na(measure) & PrefMeasure != "Hamming" & method == "BU")
art <- subset(ARTICLE,
              graph_setting == "sparse" & l == 0.3 &
                PrefMeasure != "Hamming" & method == "BU")

sim <- sim %>% mutate(
  Measure = paste(measure, which, sep = " - ")
)

ggplot() + 
    geom_boxplot(aes(x = n, y = Preformance, color = Measure),
                 data = sim) + 
    facet_grid(p ~ PrefMeasure) + 
    geom_point(aes(x = n, y = Preformance), 
               data = art, color = "black", size = 3) +
    theme(axis.title.y = element_blank())
```



&nbsp;

&nbsp;

# Low Dim: Sigma Effect

***

## Dense, Top Down
```{r, warning = FALSE, echo = FALSE}
sim <- subset(SIM, 
              graph_setting == "dense" & l == 0.3 & p != 40 &
                !is.na(measure) & PrefMeasure != "Hamming" & method == "TD")
art <- subset(ARTICLE,
              graph_setting == "dense" & l == 0.3 & p!= 40 &
                PrefMeasure != "Hamming" & method == "TD")

sim$sigma <- factor(sim$sigma)
art$sigma <- factor(art$sigma)

ggplot() + 
    geom_boxplot(aes(x = n, y = Preformance, color = sigma),
                 data = sim) + 
    facet_grid(p ~ PrefMeasure) + 
    geom_point(aes(x = n, y = Preformance), 
               data = art, color = "black", size = 3) +
    theme(axis.title.y = element_blank())
```


&nbsp;

## Dense, Bottom Up
```{r, warning = FALSE, echo = FALSE}
sim <- subset(SIM, 
              graph_setting == "dense" & l == 0.3 & p != 40 &
                !is.na(measure) & PrefMeasure != "Hamming" & method == "BU")
art <- subset(ARTICLE,
              graph_setting == "dense" & l == 0.3 & p!= 40 &
                PrefMeasure != "Hamming" & method == "BU")

sim$sigma <- factor(sim$sigma)
art$sigma <- factor(art$sigma)

ggplot() + 
    geom_boxplot(aes(x = n, y = Preformance, color = sigma),
                 data = sim) + 
    facet_grid(p ~ PrefMeasure) + 
    geom_point(aes(x = n, y = Preformance), 
               data = art, color = "black", size = 3) +
    theme(axis.title.y = element_blank())
```



&nbsp;

## Sparse, Top Down
```{r, warning = FALSE, echo = FALSE}
sim <- subset(SIM, 
              graph_setting == "sparse" & l == 0.3 & p != 40 &
                !is.na(measure) & PrefMeasure != "Hamming" & method == "TD")
art <- subset(ARTICLE,
              graph_setting == "sparse" & l == 0.3 & p!= 40 &
                PrefMeasure != "Hamming" & method == "TD")

sim$sigma <- factor(sim$sigma)
art$sigma <- factor(art$sigma)

ggplot() + 
    geom_boxplot(aes(x = n, y = Preformance, color = sigma),
                 data = sim) + 
    facet_grid(p ~ PrefMeasure) + 
    geom_point(aes(x = n, y = Preformance), 
               data = art, color = "black", size = 3) +
    theme(axis.title.y = element_blank())
```

&nbsp;

## Sparse, Bottom Up

```{r, warning = FALSE, echo = FALSE}
sim <- subset(SIM, 
              graph_setting == "sparse" & l == 0.3 & p != 40 &
                !is.na(measure) & PrefMeasure != "Hamming" & method == "BU")
art <- subset(ARTICLE,
              graph_setting == "sparse" & l == 0.3 & p!= 40 &
                PrefMeasure != "Hamming" & method == "BU")

sim$sigma <- factor(sim$sigma)
art$sigma <- factor(art$sigma)

ggplot() + 
    geom_boxplot(aes(x = n, y = Preformance, color = sigma),
                 data = sim) + 
    facet_grid(p ~ PrefMeasure) + 
    geom_point(aes(x = n, y = Preformance), 
               data = art, color = "black", size = 3) +
    theme(axis.title.y = element_blank())
```






&nbsp;

&nbsp;

# High Dim

***

## Setting A & B, HTD & HBU
```{r, warning = FALSE, echo = FALSE}
sim <- subset(SIM, graph_setting %in% c("A", "B") & 
                PrefMeasure == "Kendall" & 
                n %in% c(80, 100) & ratio %in% c("0.5", "0.75", "1"))
art <- subset(ARTICLE, graph_setting %in% c("A", "B") & 
                PrefMeasure == "Kendall"& 
                n %in% c(80, 100) & ratio %in% c("0.5", "0.75", "1"))

lev <- c("HBU (M = 0.5)", "HBU (M = 1.5)", "HBU (M = 3)", 
         "HTD (search = OMP)", "HTD (search = B&B)")

sim <- sim %>% mutate(
  Method = factor(ifelse(method == "HBU", 
                         paste0(method, " (M = ", M, ")"),
                         paste0(method, " (search = ", search, ")")), 
                  levels = lev)
)
art <- art %>% mutate(
  Method = factor(ifelse(method == "HBU", 
                         paste0(method, " (M = ", M, ")"),
                         paste0(method, " (search = ", search, ")")),
                  levels = lev)
)



ggplot() + 
    geom_boxplot(aes(x = n, y = (Preformance-50)/50, color = Method), 
                 data = sim) + 
    facet_grid(ratio ~ graph_setting) + 
    geom_point(aes(x = n, y = (Preformance-50)/50, shape = Method), 
               data = art, color = "black",
               position = position_dodge(1.2), size = 3) +
    theme(axis.title.y = element_blank())
```





